create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('admin', 'buyer', 'viewer');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.repricing_products (
  id text primary key,
  shop_name text not null,
  store_id text not null,
  sku text not null,
  tsin text,
  title text,
  offer_url text,
  canonical_url text,
  variant_label text,
  cost_price numeric default 0,
  min_price numeric default 0,
  max_price numeric default 0,
  target_price numeric default 0,
  undercut_amount numeric default 0,
  auto_reprice boolean default false,
  enabled boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shop_name, sku)
);

create table if not exists public.repricing_snapshots (
  id bigint generated by default as identity primary key,
  shop_name text not null,
  store_id text not null,
  sku text not null,
  title text,
  my_price numeric,
  buy_box_price numeric,
  lowest_competitor_price numeric,
  lowest_competitor_seller text,
  competitor_sellers text,
  price_gap numeric,
  profit numeric,
  profit_margin numeric,
  has_buy_box boolean default false,
  lost_buy_box boolean default false,
  is_out_of_stock boolean default false,
  suggested_price numeric,
  suggested_reason text,
  alert_level text not null default 'none',
  alert_type text not null default 'none',
  alert_message text,
  source text,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.repricing_alerts (
  id text primary key,
  shop_name text not null,
  store_id text not null,
  sku text not null,
  title text,
  my_price numeric,
  buy_box_price numeric,
  lowest_competitor_price numeric,
  lowest_competitor_seller text,
  price_gap numeric,
  alert_level text not null default 'none',
  alert_type text not null default 'none',
  alert_message text,
  is_active boolean not null default false,
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.repricing_logs (
  id bigint generated by default as identity primary key,
  level text not null default 'info',
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists repricing_alerts_active_idx
on public.repricing_alerts (is_active, alert_level, checked_at desc);

create index if not exists repricing_alerts_shop_sku_idx
on public.repricing_alerts (shop_name, sku);

create index if not exists repricing_snapshots_shop_sku_checked_idx
on public.repricing_snapshots (shop_name, sku, checked_at desc);

alter table public.repricing_products enable row level security;
alter table public.repricing_snapshots enable row level security;
alter table public.repricing_alerts enable row level security;
alter table public.repricing_logs enable row level security;

drop policy if exists "shared select repricing products" on public.repricing_products;
create policy "shared select repricing products" on public.repricing_products for select to authenticated using (true);

drop policy if exists "shared select repricing snapshots" on public.repricing_snapshots;
create policy "shared select repricing snapshots" on public.repricing_snapshots for select to authenticated using (true);

drop policy if exists "shared select repricing alerts" on public.repricing_alerts;
create policy "shared select repricing alerts" on public.repricing_alerts for select to authenticated using (true);

drop policy if exists "shared select repricing logs" on public.repricing_logs;
create policy "shared select repricing logs" on public.repricing_logs for select to authenticated using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'repricing_alerts'
  ) then
    alter publication supabase_realtime add table public.repricing_alerts;
  end if;
end $$;

do $$ begin
  create type public.purchase_status as enum ('in_transit', 'arrived', 'cancelled');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  buyer_name text,
  role public.app_role not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sku_items (
  id text primary key,
  sku text,
  product_name text,
  english_name text,
  image_url text,
  manufacturer_name text,
  shop_name text,
  buyer_name text,
  is_seasonal boolean default false,
  purchase_price numeric default 0,
  unit_cbm numeric default 0,
  box_length_cm numeric default 0,
  box_width_cm numeric default 0,
  box_height_cm numeric default 0,
  units_per_carton numeric default 0,
  total_quantity numeric default 0,
  total_cbm numeric default 0,
  notes text,
  cbm_source text default 'missing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sku_items
add column if not exists purchase_price numeric default 0;

alter table public.sku_items
add column if not exists unit_cbm numeric default 0;

alter table public.sku_items
add column if not exists image_url text;

alter table public.sku_items
add column if not exists box_length_cm numeric default 0;

alter table public.sku_items
add column if not exists box_width_cm numeric default 0;

alter table public.sku_items
add column if not exists box_height_cm numeric default 0;

alter table public.sku_items
add column if not exists notes text;

alter table public.profiles
add column if not exists buyer_name text;

alter table public.sku_items
add column if not exists cbm_source text default 'missing';

alter table public.sku_items
add column if not exists is_seasonal boolean default false;

alter table public.sku_items
drop column if exists note;

do $$ begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'sku_items' and column_name = 'manual_unit_cbm'
  ) then
    update public.sku_items set unit_cbm = coalesce(nullif(unit_cbm, 0), manual_unit_cbm, 0);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'sku_items' and column_name = 'carton_length_cm'
  ) then
    update public.sku_items
    set
      box_length_cm = coalesce(nullif(box_length_cm, 0), carton_length_cm, 0),
      box_width_cm = coalesce(nullif(box_width_cm, 0), carton_width_cm, 0),
      box_height_cm = coalesce(nullif(box_height_cm, 0), carton_height_cm, 0);
  end if;
end $$;

alter table public.sku_items
alter column sku drop not null;

alter table public.sku_items
drop constraint if exists sku_items_sku_key;

create table if not exists public.purchase_records (
  id text primary key,
  manufacturer_name text,
  sku text not null,
  product_name text,
  english_name text,
  image_url text,
  shop_name text,
  buyer_name text,
  assigned_buyer_name text,
  assigned_buyer_email text,
  purchase_quantity numeric not null default 0,
  purchase_price numeric not null default 0,
  total_amount numeric not null default 0,
  purchase_date date,
  estimated_arrival_date date,
  status text not null default 'pending',
  unit_cbm numeric not null default 0,
  total_cbm numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.purchase_records
add column if not exists english_name text;

alter table public.purchase_records
add column if not exists image_url text;

alter table public.purchase_records
add column if not exists assigned_buyer_name text;

alter table public.purchase_records
add column if not exists assigned_buyer_email text;

alter table public.purchase_records
add column if not exists is_confirmed boolean not null default false;

alter table public.purchase_records
add column if not exists confirmed_purchase_quantity numeric;

alter table public.purchase_records
add column if not exists unit_cbm numeric not null default 0;

alter table public.purchase_records
add column if not exists loading_type text;

alter table public.purchase_records
add column if not exists container_date date;

alter table public.purchase_records
add column if not exists total_weight_kg numeric;

alter table public.purchase_records
add column if not exists carton_count numeric;

alter table public.purchase_records
drop column if exists packing_details;

alter table public.purchase_records
drop column if exists packing_items;

alter table public.purchase_records
add column if not exists is_mixed boolean not null default false;

alter table public.purchase_records
add column if not exists units_per_carton numeric;

alter table public.purchase_records
add column if not exists tail_quantity numeric not null default 0;

alter table public.purchase_records
add column if not exists mixed_groups jsonb not null default '[]'::jsonb;

alter table public.purchase_records
add column if not exists logistics_total_cbm numeric;

alter table public.purchase_records
add column if not exists purchase_batch_id text;

alter table public.purchase_records
add column if not exists purchase_batch_name text;

alter table public.purchase_records
add column if not exists purchase_batch_date date;

alter table public.purchase_records
add column if not exists purchase_pool_id text;

alter table public.purchase_records
add column if not exists purchase_pool_name text;

alter table public.purchase_records
add column if not exists purchase_pool_date date;

alter table public.purchase_records
add column if not exists pool_status text not null default 'pending_purchase';

alter table public.purchase_records
alter column status type text using status::text;

alter table public.purchase_records
alter column status set default 'pending';

update public.purchase_records
set pool_status = 'sent_to_inventory'
where pool_status = 'pending_purchase'
  and status in ('ordered', 'in_transit', 'arrived');

create index if not exists purchase_records_assigned_buyer_email_idx
on public.purchase_records (assigned_buyer_email);

create index if not exists purchase_records_status_idx
on public.purchase_records (status);

create index if not exists purchase_records_batch_idx
on public.purchase_records (purchase_batch_date, purchase_batch_id);

create index if not exists purchase_records_pool_idx
on public.purchase_records (purchase_pool_date, purchase_pool_id, pool_status);

create index if not exists purchase_records_is_confirmed_idx
on public.purchase_records (is_confirmed);

create table if not exists public.purchase_pools (
  id text primary key,
  name text not null,
  container_date date,
  status text not null default 'open',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  sent_by uuid references auth.users(id) on delete set null,
  sent_at timestamptz,
  note text
);

create index if not exists purchase_pools_status_date_idx
on public.purchase_pools (status, container_date desc, created_at desc);

create table if not exists public.container_rows (
  id text primary key,
  row_number integer,
  sku text,
  product_name text,
  english_name text,
  manufacturer_name text,
  purchase_quantity numeric,
  raw jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.container_rows
add column if not exists product_name text;

alter table public.container_rows
add column if not exists english_name text;

alter table public.container_rows
add column if not exists manufacturer_name text;

create table if not exists public.sales_suggestions (
  id text primary key,
  sku text,
  product_name text,
  shop_name text,
  manufacturer_name text,
  buyer_name text,
  monthly_sales numeric default 0,
  stock_months numeric default 2,
  target_quantity numeric default 0,
  local_stock_quantity numeric default 0,
  takealot_stock_quantity numeric default 0,
  stock_on_way_quantity numeric default 0,
  in_transit_quantity numeric default 0,
  suggested_quantity numeric default 0,
  units_per_carton numeric,
  estimated_cartons numeric,
  estimated_cbm numeric,
  messages text[] default '{}',
  created_at timestamptz not null default now()
);

alter table public.sales_suggestions
add column if not exists local_stock_quantity numeric default 0;

alter table public.sales_suggestions
add column if not exists takealot_stock_quantity numeric default 0;

alter table public.sales_suggestions
add column if not exists stock_on_way_quantity numeric default 0;

create table if not exists public.audit_logs (
  id text primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text not null,
  actor_role public.app_role not null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  summary text not null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data->>'display_name', new.email, ''), 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_role()
returns public.app_role
language sql
security definer
stable
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.is_editor()
returns boolean
language sql
security definer
stable
as $$
  select public.current_role() in ('admin', 'buyer')
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select public.current_role() = 'admin'
$$;

alter table public.profiles enable row level security;
alter table public.sku_items enable row level security;
alter table public.purchase_records enable row level security;
alter table public.purchase_pools enable row level security;
alter table public.container_rows enable row level security;
alter table public.sales_suggestions enable row level security;
alter table public.audit_logs enable row level security;

drop policy if exists "profiles select own or admin" on public.profiles;
drop policy if exists "profiles shared select" on public.profiles;
create policy "profiles shared select" on public.profiles
for select to authenticated
using (true);

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own" on public.profiles
for insert to authenticated
with check (id = auth.uid());

drop policy if exists "profiles admin update" on public.profiles;
create policy "profiles admin update" on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "profiles update own binding" on public.profiles;
create policy "profiles update own binding" on public.profiles
for update to authenticated
using (id = auth.uid())
with check (id = auth.uid());

drop policy if exists "shared select sku" on public.sku_items;
create policy "shared select sku" on public.sku_items for select to authenticated using (true);
drop policy if exists "editor insert sku" on public.sku_items;
create policy "editor insert sku" on public.sku_items for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update sku" on public.sku_items;
create policy "editor update sku" on public.sku_items for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "admin delete sku" on public.sku_items;
create policy "admin delete sku" on public.sku_items for delete to authenticated using (public.is_admin());

drop policy if exists "shared select purchase" on public.purchase_records;
create policy "shared select purchase" on public.purchase_records for select to authenticated using (true);
drop policy if exists "editor insert purchase" on public.purchase_records;
create policy "editor insert purchase" on public.purchase_records for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update purchase" on public.purchase_records;
create policy "editor update purchase" on public.purchase_records for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "admin delete purchase" on public.purchase_records;
drop policy if exists "purchase delete own or admin" on public.purchase_records;
create policy "purchase delete own or admin" on public.purchase_records
for delete to authenticated
using (
  public.is_admin()
  or lower(coalesce(assigned_buyer_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists "shared select purchase pools" on public.purchase_pools;
create policy "shared select purchase pools" on public.purchase_pools for select to authenticated using (true);
drop policy if exists "admin insert purchase pools" on public.purchase_pools;
drop policy if exists "editor insert purchase pools" on public.purchase_pools;
create policy "editor insert purchase pools" on public.purchase_pools for insert to authenticated with check (public.is_editor());
drop policy if exists "admin update purchase pools" on public.purchase_pools;
drop policy if exists "editor update purchase pools" on public.purchase_pools;
create policy "editor update purchase pools" on public.purchase_pools for update to authenticated using (public.is_editor()) with check (public.is_editor());

drop policy if exists "shared select container" on public.container_rows;
create policy "shared select container" on public.container_rows for select to authenticated using (true);
drop policy if exists "editor insert container" on public.container_rows;
create policy "editor insert container" on public.container_rows for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update container" on public.container_rows;
create policy "editor update container" on public.container_rows for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "editor delete container" on public.container_rows;
create policy "editor delete container" on public.container_rows for delete to authenticated using (public.is_editor());

drop policy if exists "shared select suggestions" on public.sales_suggestions;
create policy "shared select suggestions" on public.sales_suggestions for select to authenticated using (true);
drop policy if exists "editor insert suggestions" on public.sales_suggestions;
create policy "editor insert suggestions" on public.sales_suggestions for insert to authenticated with check (public.is_editor());
drop policy if exists "editor delete suggestions" on public.sales_suggestions;
create policy "editor delete suggestions" on public.sales_suggestions for delete to authenticated using (public.is_editor());

drop policy if exists "shared select audit" on public.audit_logs;
create policy "shared select audit" on public.audit_logs for select to authenticated using (true);
drop policy if exists "editor insert audit" on public.audit_logs;
create policy "editor insert audit" on public.audit_logs for insert to authenticated with check (public.is_editor());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sku_items'
  ) then
    alter publication supabase_realtime add table public.sku_items;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'purchase_records'
  ) then
    alter publication supabase_realtime add table public.purchase_records;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'purchase_pools'
  ) then
    alter publication supabase_realtime add table public.purchase_pools;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'container_rows'
  ) then
    alter publication supabase_realtime add table public.container_rows;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'audit_logs'
  ) then
    alter publication supabase_realtime add table public.audit_logs;
  end if;
end $$;

-- 2026-06-08 cleanup: price alerts keep current data only, audit logs are no longer used.
delete from public.repricing_snapshots;
drop table if exists public.audit_logs cascade;

-- 2026-06-10 SKU master data optional fields used by import/export and new product sync.
alter table public.sku_items
add column if not exists storage_location text;

alter table public.sku_items
add column if not exists purchase_url text;

-- 2026-07-22 广告分析：只保留最近三次分析结果，明细随 run 删除。
create table if not exists public.ad_analysis_runs (
  id text primary key,
  created_at timestamptz not null default now(),
  created_by text,
  source_file_name text,
  row_count numeric default 0,
  summary jsonb not null default '{}'::jsonb
);

create table if not exists public.ad_analysis_rows (
  id text primary key,
  run_id text not null references public.ad_analysis_runs(id) on delete cascade,
  sku text,
  product_name text,
  shop_name text,
  image_url text,
  ad_spend numeric default 0,
  ad_sales_quantity numeric default 0,
  roas numeric,
  sale_price numeric default 0,
  platform_fee numeric default 0,
  platform_fee_source text,
  purchase_cost_rmb numeric default 0,
  purchase_cost_zar numeric default 0,
  unit_cbm numeric default 0,
  sea_freight_cost numeric default 0,
  warehouse_fee numeric default 0,
  ad_cost_per_sale numeric default 0,
  profit_rate numeric,
  sku_rank numeric,
  product_age_status text,
  strategy_label text,
  strategy_name text,
  action_suggestion text,
  messages text[] default '{}'
);

create index if not exists ad_analysis_runs_created_idx
on public.ad_analysis_runs (created_at desc);

create index if not exists ad_analysis_rows_run_idx
on public.ad_analysis_rows (run_id);

alter table public.ad_analysis_runs enable row level security;
alter table public.ad_analysis_rows enable row level security;

drop policy if exists "shared select ad analysis runs" on public.ad_analysis_runs;
create policy "shared select ad analysis runs" on public.ad_analysis_runs for select to authenticated using (true);
drop policy if exists "editor insert ad analysis runs" on public.ad_analysis_runs;
create policy "editor insert ad analysis runs" on public.ad_analysis_runs for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update ad analysis runs" on public.ad_analysis_runs;
create policy "editor update ad analysis runs" on public.ad_analysis_runs for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "editor delete ad analysis runs" on public.ad_analysis_runs;
create policy "editor delete ad analysis runs" on public.ad_analysis_runs for delete to authenticated using (public.is_editor());

drop policy if exists "shared select ad analysis rows" on public.ad_analysis_rows;
create policy "shared select ad analysis rows" on public.ad_analysis_rows for select to authenticated using (true);
drop policy if exists "editor insert ad analysis rows" on public.ad_analysis_rows;
create policy "editor insert ad analysis rows" on public.ad_analysis_rows for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update ad analysis rows" on public.ad_analysis_rows;
create policy "editor update ad analysis rows" on public.ad_analysis_rows for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "editor delete ad analysis rows" on public.ad_analysis_rows;
create policy "editor delete ad analysis rows" on public.ad_analysis_rows for delete to authenticated using (public.is_editor());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'ad_analysis_runs'
  ) then
    alter publication supabase_realtime add table public.ad_analysis_runs;
  end if;
end $$;
