create extension if not exists pgcrypto;

do $$ begin
  create type public.app_role as enum ('admin', 'buyer', 'viewer');
exception
  when duplicate_object then null;
end $$;

alter type public.app_role add value if not exists 'logistics';
alter type public.app_role add value if not exists 'owner';

create table if not exists public.repricing_products (
  id text primary key,
  shop_name text not null,
  store_id text not null,
  sku text not null,
  tsin text,
  title text,
  offer_url text,
  canonical_url text,
  variant_label text,
  cost_price numeric default 0,
  min_price numeric default 0,
  max_price numeric default 0,
  target_price numeric default 0,
  undercut_amount numeric default 0,
  auto_reprice boolean default false,
  enabled boolean default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (shop_name, sku)
);

create table if not exists public.repricing_snapshots (
  id bigint generated by default as identity primary key,
  shop_name text not null,
  store_id text not null,
  sku text not null,
  title text,
  my_price numeric,
  buy_box_price numeric,
  lowest_competitor_price numeric,
  lowest_competitor_seller text,
  competitor_sellers text,
  price_gap numeric,
  profit numeric,
  profit_margin numeric,
  has_buy_box boolean default false,
  lost_buy_box boolean default false,
  is_out_of_stock boolean default false,
  suggested_price numeric,
  suggested_reason text,
  alert_level text not null default 'none',
  alert_type text not null default 'none',
  alert_message text,
  source text,
  checked_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.repricing_alerts (
  id text primary key,
  shop_name text not null,
  store_id text not null,
  sku text not null,
  title text,
  my_price numeric,
  buy_box_price numeric,
  lowest_competitor_price numeric,
  lowest_competitor_seller text,
  price_gap numeric,
  alert_level text not null default 'none',
  alert_type text not null default 'none',
  alert_message text,
  is_active boolean not null default false,
  checked_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.repricing_logs (
  id bigint generated by default as identity primary key,
  level text not null default 'info',
  message text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists repricing_alerts_active_idx
on public.repricing_alerts (is_active, alert_level, checked_at desc);

create index if not exists repricing_alerts_shop_sku_idx
on public.repricing_alerts (shop_name, sku);

create index if not exists repricing_snapshots_shop_sku_checked_idx
on public.repricing_snapshots (shop_name, sku, checked_at desc);

alter table public.repricing_products enable row level security;
alter table public.repricing_snapshots enable row level security;
alter table public.repricing_alerts enable row level security;
alter table public.repricing_logs enable row level security;

drop policy if exists "shared select repricing products" on public.repricing_products;
create policy "shared select repricing products" on public.repricing_products for select to authenticated using (true);

drop policy if exists "shared select repricing snapshots" on public.repricing_snapshots;
create policy "shared select repricing snapshots" on public.repricing_snapshots for select to authenticated using (true);

drop policy if exists "shared select repricing alerts" on public.repricing_alerts;
create policy "shared select repricing alerts" on public.repricing_alerts for select to authenticated using (true);

drop policy if exists "shared select repricing logs" on public.repricing_logs;
create policy "shared select repricing logs" on public.repricing_logs for select to authenticated using (true);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'repricing_alerts'
  ) then
    alter publication supabase_realtime add table public.repricing_alerts;
  end if;
end $$;

do $$ begin
  create type public.purchase_status as enum ('in_transit', 'arrived', 'cancelled');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text not null,
  display_name text,
  buyer_name text,
  role public.app_role not null default 'viewer',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sku_items (
  id text primary key,
  sku text,
  tsin text,
  product_name text,
  english_name text,
  image_url text,
  manufacturer_name text,
  shop_name text,
  buyer_name text,
  is_seasonal boolean default false,
  purchase_price numeric default 0,
  unit_cbm numeric default 0,
  box_length_cm numeric default 0,
  box_width_cm numeric default 0,
  box_height_cm numeric default 0,
  units_per_carton numeric default 0,
  total_quantity numeric default 0,
  total_cbm numeric default 0,
  notes text,
  cbm_source text default 'missing',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sku_items
add column if not exists purchase_price numeric default 0;

alter table public.sku_items
add column if not exists tsin text;

alter table public.sku_items
add column if not exists internal_code text;

create unique index if not exists sku_items_internal_code_idx
on public.sku_items (internal_code)
where internal_code is not null and internal_code <> '';

with existing as (
  select coalesce(max(internal_code::integer), 0) as max_code
  from public.sku_items
  where internal_code ~ '^\d{5}$'
),
numbered as (
  select
    id,
    lpad((existing.max_code + row_number() over (
      order by coalesce(manufacturer_name, ''), coalesce(sku, ''), coalesce(product_name, ''), id
    ))::text, 5, '0') as next_code
  from public.sku_items
  cross join existing
  where coalesce(internal_code, '') = ''
)
update public.sku_items s
set internal_code = numbered.next_code
from numbered
where s.id = numbered.id;

alter table public.sku_items
add column if not exists unit_cbm numeric default 0;

alter table public.sku_items
add column if not exists image_url text;

alter table public.sku_items
add column if not exists box_length_cm numeric default 0;

alter table public.sku_items
add column if not exists box_width_cm numeric default 0;

alter table public.sku_items
add column if not exists box_height_cm numeric default 0;

alter table public.sku_items
add column if not exists notes text;

alter table public.profiles
add column if not exists buyer_name text;

alter table public.profiles
add column if not exists logistics_provider_type text;

alter table public.profiles
drop constraint if exists profiles_logistics_provider_type_check;

alter table public.profiles
add constraint profiles_logistics_provider_type_check
check (logistics_provider_type is null or logistics_provider_type in ('container', 'haichuan'));

alter table public.sku_items
add column if not exists cbm_source text default 'missing';

alter table public.sku_items
add column if not exists is_seasonal boolean default false;

alter table public.sku_items
drop column if exists note;

do $$ begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'sku_items' and column_name = 'manual_unit_cbm'
  ) then
    update public.sku_items set unit_cbm = coalesce(nullif(unit_cbm, 0), manual_unit_cbm, 0);
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'sku_items' and column_name = 'carton_length_cm'
  ) then
    update public.sku_items
    set
      box_length_cm = coalesce(nullif(box_length_cm, 0), carton_length_cm, 0),
      box_width_cm = coalesce(nullif(box_width_cm, 0), carton_width_cm, 0),
      box_height_cm = coalesce(nullif(box_height_cm, 0), carton_height_cm, 0);
  end if;
end $$;

alter table public.sku_items
alter column sku drop not null;

alter table public.sku_items
drop constraint if exists sku_items_sku_key;

create table if not exists public.purchase_records (
  id text primary key,
  manufacturer_name text,
  sku text not null,
  product_name text,
  english_name text,
  image_url text,
  shop_name text,
  buyer_name text,
  assigned_buyer_name text,
  assigned_buyer_email text,
  purchase_quantity numeric not null default 0,
  purchase_price numeric not null default 0,
  total_amount numeric not null default 0,
  purchase_date date,
  estimated_arrival_date date,
  status text not null default 'pending',
  unit_cbm numeric not null default 0,
  total_cbm numeric not null default 0,
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.purchase_records
add column if not exists english_name text;

alter table public.purchase_records
add column if not exists image_url text;

alter table public.purchase_records
add column if not exists assigned_buyer_name text;

alter table public.purchase_records
add column if not exists assigned_buyer_email text;

alter table public.purchase_records
add column if not exists is_confirmed boolean not null default false;

alter table public.purchase_records
add column if not exists confirmed_purchase_quantity numeric;

alter table public.purchase_records
add column if not exists unit_cbm numeric not null default 0;

alter table public.purchase_records
add column if not exists loading_type text;

alter table public.purchase_records
add column if not exists container_date date;

alter table public.purchase_records
add column if not exists total_weight_kg numeric;

alter table public.purchase_records
add column if not exists carton_count numeric;

alter table public.purchase_records
drop column if exists packing_details;

alter table public.purchase_records
drop column if exists packing_items;

alter table public.purchase_records
add column if not exists is_mixed boolean not null default false;

alter table public.purchase_records
add column if not exists units_per_carton numeric;

alter table public.purchase_records
add column if not exists tail_quantity numeric not null default 0;

alter table public.purchase_records
add column if not exists mixed_groups jsonb not null default '[]'::jsonb;

alter table public.purchase_records
add column if not exists logistics_total_cbm numeric;

alter table public.purchase_records
add column if not exists internal_code text;

alter table public.purchase_records
add column if not exists logistics_batch_id text;

alter table public.purchase_records
add column if not exists logistics_confirmation_status text not null default 'unassigned';

alter table public.purchase_records
add column if not exists logistics_loaded_carton_count numeric;

alter table public.purchase_records
add column if not exists logistics_loaded_tail_quantity numeric not null default 0;

alter table public.purchase_records
add column if not exists logistics_left_carton_count numeric;

alter table public.purchase_records
add column if not exists logistics_left_tail_quantity numeric not null default 0;

alter table public.purchase_records
add column if not exists logistics_source_record_id text;

alter table public.purchase_records
add column if not exists purchase_batch_id text;

alter table public.purchase_records
add column if not exists purchase_batch_name text;

alter table public.purchase_records
add column if not exists purchase_batch_date date;

alter table public.purchase_records
add column if not exists purchase_pool_id text;

alter table public.purchase_records
add column if not exists purchase_pool_name text;

alter table public.purchase_records
add column if not exists purchase_pool_date date;

alter table public.purchase_records
add column if not exists pool_status text not null default 'pending_purchase';

alter table public.purchase_records
add column if not exists freight_cost numeric not null default 0;

alter table public.purchase_records
alter column status type text using status::text;

alter table public.purchase_records
alter column status set default 'pending';

update public.purchase_records
set pool_status = 'sent_to_inventory'
where pool_status = 'pending_purchase'
  and status in ('ordered', 'in_transit', 'arrived');

create index if not exists purchase_records_assigned_buyer_email_idx
on public.purchase_records (assigned_buyer_email);

create index if not exists purchase_records_status_idx
on public.purchase_records (status);

create index if not exists purchase_records_batch_idx
on public.purchase_records (purchase_batch_date, purchase_batch_id);

create index if not exists purchase_records_pool_idx
on public.purchase_records (purchase_pool_date, purchase_pool_id, pool_status);

create index if not exists purchase_records_is_confirmed_idx
on public.purchase_records (is_confirmed);

create table if not exists public.logistics_batches (
  id text primary key,
  container_date date not null,
  logistics_user_id uuid references auth.users(id) on delete set null,
  logistics_email text,
  status text not null default 'draft',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  submitted_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  note text not null default ''
);

create table if not exists public.logistics_batch_items (
  id text primary key,
  batch_id text not null references public.logistics_batches(id) on delete cascade,
  purchase_record_id text,
  internal_code text,
  manufacturer_name text,
  sku text,
  product_name text,
  english_name text,
  image_url text,
  shop_name text,
  container_date date,
  carton_count numeric,
  units_per_carton numeric,
  tail_quantity numeric not null default 0,
  total_quantity numeric not null default 0,
  loading_type text,
  is_mixed boolean not null default false,
  mixed_groups_summary text,
  loaded_carton_count numeric,
  loaded_tail_quantity numeric not null default 0,
  left_carton_count numeric,
  left_tail_quantity numeric not null default 0,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.logistics_batch_items
add column if not exists total_quantity numeric not null default 0;

create index if not exists logistics_batches_container_date_idx
on public.logistics_batches (container_date desc);

create index if not exists logistics_batches_user_idx
on public.logistics_batches (logistics_user_id, status);

create index if not exists logistics_batch_items_batch_idx
on public.logistics_batch_items (batch_id, internal_code);

create table if not exists public.haichuan_inbound_items (
  id text primary key,
  purchase_record_id text not null unique references public.purchase_records(id) on delete restrict,
  logistics_user_id uuid references auth.users(id) on delete set null,
  logistics_email text,
  internal_code text,
  manufacturer_name text,
  sku text,
  product_name text,
  english_name text,
  image_url text,
  shop_name text,
  buyer_name text,
  purchase_total_quantity numeric not null default 0,
  declared_carton_count integer not null default 0,
  declared_units_per_carton numeric not null default 0,
  declared_tail_quantity numeric not null default 0,
  declared_total_carton_count integer not null default 0,
  actual_received_carton_count integer,
  unit_cbm numeric not null default 0,
  declared_total_cbm numeric not null default 0,
  product_details jsonb not null default '[]'::jsonb,
  has_packing_variance boolean not null default false,
  status text not null default 'pending_receipt' check (status in ('pending_receipt', 'received')),
  received_by uuid references auth.users(id) on delete set null,
  received_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.haichuan_warehouse_lots (
  id text primary key,
  inbound_item_id text not null unique references public.haichuan_inbound_items(id) on delete restrict,
  purchase_record_id text not null references public.purchase_records(id) on delete restrict,
  logistics_user_id uuid references auth.users(id) on delete set null,
  logistics_email text,
  internal_code text,
  manufacturer_name text,
  sku text,
  product_name text,
  english_name text,
  image_url text,
  shop_name text,
  buyer_name text,
  declared_carton_count integer not null default 0,
  declared_units_per_carton numeric not null default 0,
  declared_tail_quantity numeric not null default 0,
  initial_carton_count integer not null,
  remaining_carton_count integer not null,
  reserved_carton_count integer not null default 0,
  initial_product_quantity numeric not null,
  remaining_product_quantity numeric not null,
  initial_cbm numeric not null default 0,
  remaining_cbm numeric not null default 0,
  unit_cbm numeric not null default 0,
  product_details jsonb not null default '[]'::jsonb,
  has_packing_variance boolean not null default false,
  status text not null default 'available' check (status in ('available', 'partially_reserved', 'fully_reserved', 'depleted')),
  version integer not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (remaining_carton_count >= 0),
  check (reserved_carton_count >= 0),
  check (reserved_carton_count <= remaining_carton_count),
  check (remaining_product_quantity >= 0),
  check (remaining_cbm >= 0)
);

create table if not exists public.haichuan_loading_batches (
  id text primary key,
  container_date date not null,
  logistics_user_id uuid references auth.users(id) on delete set null,
  logistics_email text,
  status text not null default 'draft' check (status in ('draft', 'submitted', 'approved', 'rejected')),
  created_by uuid references auth.users(id) on delete set null,
  submitted_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  note text not null default '',
  rejection_reason text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.haichuan_loading_items (
  id text primary key,
  batch_id text not null references public.haichuan_loading_batches(id) on delete cascade,
  warehouse_lot_id text not null references public.haichuan_warehouse_lots(id) on delete restrict,
  purchase_record_id text not null references public.purchase_records(id) on delete restrict,
  internal_code text,
  sku text,
  product_name text,
  requested_carton_count integer not null,
  suggested_product_quantity numeric not null default 0,
  suggested_cbm numeric not null default 0,
  is_estimated boolean not null default false,
  approved_carton_count integer,
  approved_product_quantity numeric,
  approved_cbm numeric,
  product_details jsonb not null default '[]'::jsonb,
  warehouse_version integer not null default 1,
  note text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (batch_id, warehouse_lot_id)
);

alter table public.haichuan_inbound_items
add column if not exists product_details jsonb not null default '[]'::jsonb;

alter table public.haichuan_warehouse_lots
add column if not exists product_details jsonb not null default '[]'::jsonb;

alter table public.haichuan_loading_items
add column if not exists product_details jsonb not null default '[]'::jsonb;

create index if not exists haichuan_inbound_assignee_status_idx
on public.haichuan_inbound_items (logistics_user_id, status, created_at desc);

create index if not exists haichuan_warehouse_assignee_status_idx
on public.haichuan_warehouse_lots (logistics_user_id, status, created_at desc);

create index if not exists haichuan_loading_assignee_status_idx
on public.haichuan_loading_batches (logistics_user_id, status, container_date desc);

create index if not exists haichuan_loading_items_batch_idx
on public.haichuan_loading_items (batch_id, warehouse_lot_id);

create table if not exists public.purchase_pools (
  id text primary key,
  name text not null,
  container_date date,
  status text not null default 'open',
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  sent_by uuid references auth.users(id) on delete set null,
  sent_at timestamptz,
  note text
);

create index if not exists purchase_pools_status_date_idx
on public.purchase_pools (status, container_date desc, created_at desc);

create table if not exists public.container_rows (
  id text primary key,
  row_number integer,
  internal_code text,
  sku text,
  product_name text,
  english_name text,
  manufacturer_name text,
  purchase_quantity numeric,
  raw jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.container_rows
add column if not exists product_name text;

alter table public.container_rows
add column if not exists english_name text;

alter table public.container_rows
add column if not exists manufacturer_name text;

alter table public.container_rows
add column if not exists internal_code text;

create table if not exists public.sales_suggestions (
  id text primary key,
  sku text,
  product_name text,
  shop_name text,
  manufacturer_name text,
  buyer_name text,
  monthly_sales numeric default 0,
  stock_months numeric default 2,
  target_quantity numeric default 0,
  local_stock_quantity numeric default 0,
  takealot_stock_quantity numeric default 0,
  stock_on_way_quantity numeric default 0,
  in_transit_quantity numeric default 0,
  suggested_quantity numeric default 0,
  units_per_carton numeric,
  estimated_cartons numeric,
  estimated_cbm numeric,
  messages text[] default '{}',
  created_at timestamptz not null default now()
);

alter table public.sales_suggestions
add column if not exists local_stock_quantity numeric default 0;

alter table public.sales_suggestions
add column if not exists takealot_stock_quantity numeric default 0;

alter table public.sales_suggestions
add column if not exists stock_on_way_quantity numeric default 0;

create table if not exists public.audit_logs (
  id text primary key,
  actor_id uuid references auth.users(id) on delete set null,
  actor_email text not null,
  actor_role public.app_role not null,
  action text not null,
  entity_type text not null,
  entity_id text not null,
  summary text not null,
  metadata jsonb default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, email, display_name, role)
  values (new.id, coalesce(new.email, ''), coalesce(new.raw_user_meta_data->>'display_name', new.email, ''), 'viewer')
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create or replace function public.current_role()
returns public.app_role
language sql
security definer
stable
as $$
  select role from public.profiles where id = auth.uid()
$$;

create or replace function public.is_editor()
returns boolean
language sql
security definer
stable
as $$
  select public.current_role()::text in ('owner', 'admin', 'buyer')
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
as $$
  select public.current_role()::text in ('owner', 'admin')
$$;

create or replace function public.is_owner()
returns boolean
language sql
security definer
stable
as $$
  select public.current_role()::text = 'owner'
$$;

create or replace function public.haichuan_lot_status(p_remaining integer, p_reserved integer)
returns text
language sql
immutable
as $$
  select case
    when p_remaining <= 0 then 'depleted'
    when p_reserved <= 0 then 'available'
    when p_reserved >= p_remaining then 'fully_reserved'
    else 'partially_reserved'
  end
$$;

create or replace function public.confirm_haichuan_receipt(p_inbound_id text, p_actual_carton_count integer)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_inbound public.haichuan_inbound_items%rowtype;
  v_lot_id text;
begin
  if p_actual_carton_count is null or p_actual_carton_count <= 0 then
    raise exception '实际入仓总件数必须大于 0';
  end if;

  select * into v_inbound
  from public.haichuan_inbound_items
  where id = p_inbound_id
  for update;

  if not found then raise exception '待入仓记录不存在'; end if;
  if not (
    public.is_admin()
    or v_inbound.logistics_user_id = auth.uid()
    or lower(coalesce(v_inbound.logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
  ) then raise exception '无权确认该入仓记录'; end if;

  v_lot_id := 'hc-lot-' || v_inbound.id;
  if v_inbound.status = 'received' then return v_lot_id; end if;

  insert into public.haichuan_warehouse_lots (
    id, inbound_item_id, purchase_record_id, logistics_user_id, logistics_email,
    internal_code, manufacturer_name, sku, product_name, english_name, image_url, shop_name, buyer_name,
    declared_carton_count, declared_units_per_carton, declared_tail_quantity,
    initial_carton_count, remaining_carton_count, reserved_carton_count,
    initial_product_quantity, remaining_product_quantity, initial_cbm, remaining_cbm, unit_cbm, product_details,
    has_packing_variance, status
  ) values (
    v_lot_id, v_inbound.id, v_inbound.purchase_record_id, v_inbound.logistics_user_id, v_inbound.logistics_email,
    v_inbound.internal_code, v_inbound.manufacturer_name, v_inbound.sku, v_inbound.product_name,
    v_inbound.english_name, v_inbound.image_url, v_inbound.shop_name, v_inbound.buyer_name,
    v_inbound.declared_carton_count, v_inbound.declared_units_per_carton, v_inbound.declared_tail_quantity,
    p_actual_carton_count, p_actual_carton_count, 0,
    v_inbound.purchase_total_quantity, v_inbound.purchase_total_quantity,
    v_inbound.declared_total_cbm, v_inbound.declared_total_cbm, v_inbound.unit_cbm, v_inbound.product_details,
    p_actual_carton_count <> v_inbound.declared_total_carton_count, 'available'
  ) on conflict (inbound_item_id) do nothing;

  update public.haichuan_inbound_items
  set actual_received_carton_count = p_actual_carton_count,
      has_packing_variance = p_actual_carton_count <> declared_total_carton_count,
      status = 'received', received_by = auth.uid(), received_at = now(), updated_at = now()
  where id = p_inbound_id and status = 'pending_receipt';

  update public.purchase_records
  set pool_status = 'haichuan_warehouse', updated_at = now()
  where id = v_inbound.purchase_record_id and pool_status = 'submitted_to_pool';

  return v_lot_id;
end;
$$;

create or replace function public.submit_haichuan_loading_batch(
  p_batch_id text,
  p_container_date date,
  p_note text,
  p_items jsonb
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_email text := coalesce(auth.jwt() ->> 'email', '');
  v_item jsonb;
  v_lot public.haichuan_warehouse_lots%rowtype;
  v_requested integer;
  v_available integer;
  v_quantity numeric;
  v_cbm numeric;
  v_estimated boolean;
  v_existing_status text;
begin
  if coalesce(p_batch_id, '') = '' then raise exception '装柜批次编号不能为空'; end if;
  if p_container_date is null then raise exception '请填写装柜日期'; end if;
  if jsonb_array_length(coalesce(p_items, '[]'::jsonb)) = 0 then raise exception '请选择需要装柜的库存'; end if;

  select status into v_existing_status from public.haichuan_loading_batches where id = p_batch_id for update;
  if v_existing_status in ('submitted', 'approved') then return p_batch_id; end if;

  insert into public.haichuan_loading_batches (
    id, container_date, logistics_user_id, logistics_email, status, created_by, submitted_at, note, created_at, updated_at
  ) values (
    p_batch_id, p_container_date, auth.uid(), v_email, 'draft', auth.uid(), null, coalesce(p_note, ''), now(), now()
  ) on conflict (id) do update set
    container_date = excluded.container_date,
    note = excluded.note,
    status = 'draft',
    rejection_reason = '',
    reviewed_by = null,
    reviewed_at = null,
    updated_at = now();

  delete from public.haichuan_loading_items where batch_id = p_batch_id;

  for v_item in select * from jsonb_array_elements(p_items)
  loop
    select * into v_lot
    from public.haichuan_warehouse_lots
    where id = v_item->>'warehouseLotId'
    for update;
    if not found then raise exception '海川仓库记录不存在'; end if;
    if not (
      public.is_admin()
      or v_lot.logistics_user_id = auth.uid()
      or lower(coalesce(v_lot.logistics_email, '')) = lower(v_email)
    ) then raise exception '无权操作该仓库记录'; end if;

    v_requested := floor(coalesce((v_item->>'requestedCartonCount')::numeric, 0));
    v_available := v_lot.remaining_carton_count - v_lot.reserved_carton_count;
    if v_requested <= 0 or v_requested > v_available then
      raise exception '装柜件数超过当前可用库存';
    end if;
    if jsonb_array_length(coalesce(v_lot.product_details, '[]'::jsonb)) > 1
       and v_requested <> v_lot.remaining_carton_count then
      raise exception '包含混装商品的海川库存必须整批装走或整批保留，不能部分拆分';
    end if;

    if v_requested = v_lot.remaining_carton_count then
      v_quantity := v_lot.remaining_product_quantity;
      v_cbm := v_lot.remaining_cbm;
      v_estimated := false;
    elsif v_lot.has_packing_variance then
      v_quantity := floor(v_lot.remaining_product_quantity * v_requested / nullif(v_lot.remaining_carton_count, 0));
      v_cbm := v_lot.remaining_cbm * v_requested / nullif(v_lot.remaining_carton_count, 0);
      v_estimated := true;
    else
      v_quantity := least(v_lot.remaining_product_quantity, v_requested * v_lot.declared_units_per_carton);
      v_cbm := v_quantity * v_lot.unit_cbm;
      v_estimated := false;
    end if;

    insert into public.haichuan_loading_items (
      id, batch_id, warehouse_lot_id, purchase_record_id, internal_code, sku, product_name,
      requested_carton_count, suggested_product_quantity, suggested_cbm, is_estimated, product_details,
      warehouse_version, note, created_at, updated_at
    ) values (
      p_batch_id || '-' || v_lot.id, p_batch_id, v_lot.id, v_lot.purchase_record_id,
      v_lot.internal_code, v_lot.sku, v_lot.product_name,
      v_requested, v_quantity, v_cbm, v_estimated, v_lot.product_details, v_lot.version,
      coalesce(v_item->>'note', ''), now(), now()
    );

    update public.haichuan_warehouse_lots
    set reserved_carton_count = reserved_carton_count + v_requested,
        status = public.haichuan_lot_status(remaining_carton_count, reserved_carton_count + v_requested),
        version = version + 1, updated_at = now()
    where id = v_lot.id;
  end loop;

  update public.haichuan_loading_batches
  set status = 'submitted', submitted_at = now(), updated_at = now()
  where id = p_batch_id;
  return p_batch_id;
end;
$$;

create or replace function public.review_haichuan_loading_batch(
  p_batch_id text,
  p_container_date date,
  p_note text,
  p_items jsonb,
  p_approve boolean,
  p_rejection_reason text default ''
)
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  v_batch public.haichuan_loading_batches%rowtype;
  v_item jsonb;
  v_saved public.haichuan_loading_items%rowtype;
  v_lot public.haichuan_warehouse_lots%rowtype;
  v_source public.purchase_records%rowtype;
  v_cartons integer;
  v_quantity numeric;
  v_cbm numeric;
  v_max_cartons integer;
  v_record_id text;
  v_source_quantity numeric;
  v_expected_item_count integer;
  v_payload_item_count integer;
  v_payload_distinct_count integer;
begin
  if not public.is_admin() then raise exception '只有管理员可以审核海川装柜'; end if;
  select * into v_batch from public.haichuan_loading_batches where id = p_batch_id for update;
  if not found then raise exception '海川装柜批次不存在'; end if;
  if (v_batch.status = 'approved' and p_approve) or (v_batch.status = 'rejected' and not p_approve) then
    return p_batch_id;
  end if;
  if v_batch.status <> 'submitted' then raise exception '该批次不是待审核状态'; end if;

  if not p_approve then
    for v_saved in select * from public.haichuan_loading_items where batch_id = p_batch_id
    loop
      select value into v_item
      from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
      where value->>'id' = v_saved.id
      limit 1;
      if v_item is not null then
        update public.haichuan_loading_items
        set approved_carton_count = coalesce((v_item->>'approvedCartonCount')::numeric, requested_carton_count),
            approved_product_quantity = coalesce((v_item->>'approvedProductQuantity')::numeric, suggested_product_quantity),
            approved_cbm = coalesce((v_item->>'approvedCbm')::numeric, suggested_cbm),
            note = coalesce(v_item->>'note', note),
            updated_at = now()
        where id = v_saved.id;
      end if;
      select * into v_lot from public.haichuan_warehouse_lots where id = v_saved.warehouse_lot_id for update;
      update public.haichuan_warehouse_lots
      set reserved_carton_count = greatest(0, reserved_carton_count - v_saved.requested_carton_count),
          status = public.haichuan_lot_status(remaining_carton_count, greatest(0, reserved_carton_count - v_saved.requested_carton_count)),
          version = version + 1, updated_at = now()
      where id = v_lot.id;
    end loop;
    update public.haichuan_loading_batches
    set status = 'rejected', container_date = coalesce(p_container_date, container_date), note = coalesce(p_note, note),
        rejection_reason = coalesce(p_rejection_reason, ''), reviewed_by = auth.uid(), reviewed_at = now(), updated_at = now()
    where id = p_batch_id;
    return p_batch_id;
  end if;

  select count(*) into v_expected_item_count from public.haichuan_loading_items where batch_id = p_batch_id;
  select count(*), count(distinct value->>'id')
  into v_payload_item_count, v_payload_distinct_count
  from jsonb_array_elements(coalesce(p_items, '[]'::jsonb));
  if v_payload_item_count <> v_expected_item_count or v_payload_distinct_count <> v_expected_item_count then
    raise exception '审核明细不完整或存在重复记录';
  end if;

  for v_item in select * from jsonb_array_elements(coalesce(p_items, '[]'::jsonb))
  loop
    select * into v_saved from public.haichuan_loading_items where id = v_item->>'id' and batch_id = p_batch_id for update;
    if not found then raise exception '装柜明细不存在'; end if;
    select * into v_lot from public.haichuan_warehouse_lots where id = v_saved.warehouse_lot_id for update;
    select * into v_source from public.purchase_records where id = v_saved.purchase_record_id;

    v_cartons := floor(coalesce((v_item->>'approvedCartonCount')::numeric, v_saved.requested_carton_count));
    v_quantity := coalesce((v_item->>'approvedProductQuantity')::numeric, v_saved.suggested_product_quantity);
    v_cbm := coalesce((v_item->>'approvedCbm')::numeric, v_saved.suggested_cbm);
    v_max_cartons := v_lot.remaining_carton_count - v_lot.reserved_carton_count + v_saved.requested_carton_count;
    if v_cartons < 0 or v_cartons > v_max_cartons then raise exception '审核装柜件数超过可用库存'; end if;
    if v_quantity < 0 or v_quantity > v_lot.remaining_product_quantity then raise exception '审核产品数量超过仓库库存'; end if;
    if v_cbm < 0 or v_cbm > v_lot.remaining_cbm + 0.000001 then raise exception '审核 CBM 超过仓库库存'; end if;
    if (v_cartons = 0 and (v_quantity <> 0 or v_cbm <> 0)) or (v_cartons > 0 and v_quantity <= 0) then
      raise exception '审核件数、产品数量和 CBM 不一致';
    end if;

    if v_cartons = v_lot.remaining_carton_count then
      v_quantity := v_lot.remaining_product_quantity;
      v_cbm := v_lot.remaining_cbm;
    end if;

    update public.haichuan_loading_items
    set approved_carton_count = v_cartons, approved_product_quantity = v_quantity, approved_cbm = v_cbm,
        note = coalesce(v_item->>'note', note), updated_at = now()
    where id = v_saved.id;

    update public.haichuan_warehouse_lots
    set remaining_carton_count = remaining_carton_count - v_cartons,
        reserved_carton_count = greatest(0, reserved_carton_count - v_saved.requested_carton_count),
        remaining_product_quantity = remaining_product_quantity - v_quantity,
        remaining_cbm = greatest(0, remaining_cbm - v_cbm),
        status = public.haichuan_lot_status(
          remaining_carton_count - v_cartons,
          greatest(0, reserved_carton_count - v_saved.requested_carton_count)
        ),
        version = version + 1, updated_at = now()
    where id = v_lot.id;

    if v_cartons > 0 and v_quantity > 0 then
      v_record_id := 'hc-transit-' || v_saved.id;
      v_source_quantity := greatest(v_lot.initial_product_quantity, 1);
      insert into public.purchase_records (
        id, internal_code, manufacturer_name, sku, product_name, english_name, image_url,
        freight_cost, shop_name, buyer_name, assigned_buyer_name, assigned_buyer_email,
        is_confirmed, purchase_quantity, confirmed_purchase_quantity, purchase_price, total_amount,
        purchase_date, purchase_pool_id, purchase_pool_name, purchase_pool_date, pool_status,
        purchase_batch_id, purchase_batch_name, purchase_batch_date, estimated_arrival_date, status,
        unit_cbm, total_cbm, loading_type, container_date, total_weight_kg,
        carton_count, units_per_carton, tail_quantity, is_mixed, mixed_groups,
        logistics_total_cbm, logistics_batch_id, logistics_confirmation_status, logistics_source_record_id,
        note, created_at, updated_at
      ) values (
        v_record_id, v_source.internal_code, v_source.manufacturer_name, v_source.sku, v_source.product_name,
        v_source.english_name, v_source.image_url,
        coalesce(v_source.freight_cost, 0) * v_quantity / v_source_quantity,
        v_source.shop_name, v_source.buyer_name, v_source.assigned_buyer_name, v_source.assigned_buyer_email,
        true,
        case when jsonb_array_length(coalesce(v_source.mixed_groups, '[]'::jsonb)) > 0
          then coalesce(v_source.confirmed_purchase_quantity, v_source.purchase_quantity, 0)
          else v_quantity end,
        case when jsonb_array_length(coalesce(v_source.mixed_groups, '[]'::jsonb)) > 0
          then coalesce(v_source.confirmed_purchase_quantity, v_source.purchase_quantity, 0)
          else v_quantity end,
        v_source.purchase_price,
        coalesce(v_source.total_amount, 0) * v_quantity / v_source_quantity,
        v_source.purchase_date, v_source.purchase_pool_id, v_source.purchase_pool_name, v_source.purchase_pool_date,
        'sent_to_inventory', v_source.purchase_batch_id, v_source.purchase_batch_name, v_source.purchase_batch_date,
        v_source.estimated_arrival_date, 'in_transit', v_source.unit_cbm, v_cbm, '海川',
        coalesce(p_container_date, v_batch.container_date), v_source.total_weight_kg,
        v_cartons, v_source.units_per_carton, 0, v_source.is_mixed, v_source.mixed_groups,
        v_cbm, p_batch_id, 'approved', v_source.id,
        trim(concat_ws('；', nullif(v_source.note, ''), '海川装柜审核确认')), now(), now()
      ) on conflict (id) do nothing;
    end if;
  end loop;

  update public.haichuan_loading_batches
  set status = 'approved', container_date = coalesce(p_container_date, container_date), note = coalesce(p_note, note),
      rejection_reason = '', reviewed_by = auth.uid(), reviewed_at = now(), updated_at = now()
  where id = p_batch_id;
  return p_batch_id;
end;
$$;

alter table public.profiles enable row level security;
alter table public.sku_items enable row level security;
alter table public.purchase_records enable row level security;
alter table public.purchase_pools enable row level security;
alter table public.container_rows enable row level security;
alter table public.sales_suggestions enable row level security;
alter table public.audit_logs enable row level security;
alter table public.logistics_batches enable row level security;
alter table public.logistics_batch_items enable row level security;
alter table public.haichuan_inbound_items enable row level security;
alter table public.haichuan_warehouse_lots enable row level security;
alter table public.haichuan_loading_batches enable row level security;
alter table public.haichuan_loading_items enable row level security;

drop policy if exists "profiles select own or admin" on public.profiles;
drop policy if exists "profiles shared select" on public.profiles;
create policy "profiles shared select" on public.profiles
for select to authenticated
using (coalesce(public.current_role()::text, '') <> 'logistics' or id = auth.uid() or public.is_admin());

drop policy if exists "profiles insert own" on public.profiles;
create policy "profiles insert own" on public.profiles
for insert to authenticated
with check (id = auth.uid());

drop policy if exists "profiles admin update" on public.profiles;
create policy "profiles admin update" on public.profiles
for update to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "profiles update own binding" on public.profiles;
create policy "profiles update own binding" on public.profiles
for update to authenticated
using (id = auth.uid() and coalesce(public.current_role()::text, '') <> 'logistics')
with check (id = auth.uid() and coalesce(public.current_role()::text, '') <> 'logistics');

drop policy if exists "shared select sku" on public.sku_items;
create policy "shared select sku" on public.sku_items for select to authenticated using (coalesce(public.current_role()::text, '') <> 'logistics');
drop policy if exists "editor insert sku" on public.sku_items;
create policy "editor insert sku" on public.sku_items for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update sku" on public.sku_items;
create policy "editor update sku" on public.sku_items for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "admin delete sku" on public.sku_items;
create policy "admin delete sku" on public.sku_items for delete to authenticated using (public.is_admin());

drop policy if exists "shared select purchase" on public.purchase_records;
create policy "shared select purchase" on public.purchase_records for select to authenticated using (coalesce(public.current_role()::text, '') <> 'logistics');
drop policy if exists "editor insert purchase" on public.purchase_records;
create policy "editor insert purchase" on public.purchase_records for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update purchase" on public.purchase_records;
create policy "editor update purchase" on public.purchase_records for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "admin delete purchase" on public.purchase_records;
drop policy if exists "purchase delete own or admin" on public.purchase_records;
create policy "purchase delete own or admin" on public.purchase_records
for delete to authenticated
using (
  public.is_admin()
  or lower(coalesce(assigned_buyer_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists "shared select purchase pools" on public.purchase_pools;
create policy "shared select purchase pools" on public.purchase_pools for select to authenticated using (coalesce(public.current_role()::text, '') <> 'logistics');
drop policy if exists "admin insert purchase pools" on public.purchase_pools;
drop policy if exists "editor insert purchase pools" on public.purchase_pools;
create policy "editor insert purchase pools" on public.purchase_pools for insert to authenticated with check (public.is_editor());
drop policy if exists "admin update purchase pools" on public.purchase_pools;
drop policy if exists "editor update purchase pools" on public.purchase_pools;
create policy "editor update purchase pools" on public.purchase_pools for update to authenticated using (public.is_editor()) with check (public.is_editor());

drop policy if exists "admin select logistics batches" on public.logistics_batches;
drop policy if exists "logistics select assigned batches" on public.logistics_batches;
create policy "logistics select assigned batches" on public.logistics_batches
for select to authenticated
using (
  public.is_admin()
  or logistics_user_id = auth.uid()
  or lower(coalesce(logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists "admin write logistics batches" on public.logistics_batches;
create policy "admin write logistics batches" on public.logistics_batches
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "logistics update assigned batches" on public.logistics_batches;
create policy "logistics update assigned batches" on public.logistics_batches
for update to authenticated
using (
  status in ('draft', 'rejected')
  and (
    logistics_user_id = auth.uid()
    or lower(coalesce(logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
  )
)
with check (
  status in ('draft', 'submitted')
  and (
    logistics_user_id = auth.uid()
    or lower(coalesce(logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
  )
);

drop policy if exists "logistics select assigned items" on public.logistics_batch_items;
create policy "logistics select assigned items" on public.logistics_batch_items
for select to authenticated
using (
  exists (
    select 1 from public.logistics_batches b
    where b.id = batch_id
      and (
        public.is_admin()
        or b.logistics_user_id = auth.uid()
        or lower(coalesce(b.logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  )
);

drop policy if exists "admin write logistics items" on public.logistics_batch_items;
create policy "admin write logistics items" on public.logistics_batch_items
for all to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "logistics update assigned items" on public.logistics_batch_items;
create policy "logistics update assigned items" on public.logistics_batch_items
for update to authenticated
using (
  exists (
    select 1 from public.logistics_batches b
    where b.id = batch_id
      and b.status in ('draft', 'rejected')
      and (
        b.logistics_user_id = auth.uid()
        or lower(coalesce(b.logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  )
)
with check (
  exists (
    select 1 from public.logistics_batches b
    where b.id = batch_id
      and b.status in ('draft', 'rejected')
      and (
        b.logistics_user_id = auth.uid()
        or lower(coalesce(b.logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  )
);

drop policy if exists "haichuan inbound select" on public.haichuan_inbound_items;
create policy "haichuan inbound select" on public.haichuan_inbound_items
for select to authenticated using (
  public.is_admin()
  or logistics_user_id = auth.uid()
  or lower(coalesce(logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists "editor create haichuan inbound" on public.haichuan_inbound_items;
create policy "editor create haichuan inbound" on public.haichuan_inbound_items
for insert to authenticated with check (public.is_editor());

drop policy if exists "admin update haichuan inbound" on public.haichuan_inbound_items;
create policy "admin update haichuan inbound" on public.haichuan_inbound_items
for update to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin delete pending haichuan inbound" on public.haichuan_inbound_items;
create policy "admin delete pending haichuan inbound" on public.haichuan_inbound_items
for delete to authenticated using (public.is_admin() and status = 'pending_receipt');

drop policy if exists "haichuan warehouse select" on public.haichuan_warehouse_lots;
create policy "haichuan warehouse select" on public.haichuan_warehouse_lots
for select to authenticated using (
  public.is_admin()
  or logistics_user_id = auth.uid()
  or lower(coalesce(logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists "admin write haichuan warehouse" on public.haichuan_warehouse_lots;
create policy "admin write haichuan warehouse" on public.haichuan_warehouse_lots
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "haichuan loading batch select" on public.haichuan_loading_batches;
create policy "haichuan loading batch select" on public.haichuan_loading_batches
for select to authenticated using (
  public.is_admin()
  or logistics_user_id = auth.uid()
  or lower(coalesce(logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
);

drop policy if exists "haichuan loading item select" on public.haichuan_loading_items;
create policy "haichuan loading item select" on public.haichuan_loading_items
for select to authenticated using (
  exists (
    select 1 from public.haichuan_loading_batches b
    where b.id = batch_id
      and (
        public.is_admin()
        or b.logistics_user_id = auth.uid()
        or lower(coalesce(b.logistics_email, '')) = lower(coalesce(auth.jwt() ->> 'email', ''))
      )
  )
);

drop policy if exists "admin write haichuan loading batches" on public.haichuan_loading_batches;
create policy "admin write haichuan loading batches" on public.haichuan_loading_batches
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "admin write haichuan loading items" on public.haichuan_loading_items;
create policy "admin write haichuan loading items" on public.haichuan_loading_items
for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists "shared select container" on public.container_rows;
create policy "shared select container" on public.container_rows for select to authenticated using (coalesce(public.current_role()::text, '') <> 'logistics');
drop policy if exists "editor insert container" on public.container_rows;
create policy "editor insert container" on public.container_rows for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update container" on public.container_rows;
create policy "editor update container" on public.container_rows for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "editor delete container" on public.container_rows;
create policy "editor delete container" on public.container_rows for delete to authenticated using (public.is_editor());

drop policy if exists "shared select suggestions" on public.sales_suggestions;
create policy "shared select suggestions" on public.sales_suggestions for select to authenticated using (true);
drop policy if exists "editor insert suggestions" on public.sales_suggestions;
create policy "editor insert suggestions" on public.sales_suggestions for insert to authenticated with check (public.is_editor());
drop policy if exists "editor delete suggestions" on public.sales_suggestions;
create policy "editor delete suggestions" on public.sales_suggestions for delete to authenticated using (public.is_editor());

drop policy if exists "shared select audit" on public.audit_logs;
create policy "shared select audit" on public.audit_logs for select to authenticated using (true);
drop policy if exists "editor insert audit" on public.audit_logs;
create policy "editor insert audit" on public.audit_logs for insert to authenticated with check (public.is_editor());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sku_items'
  ) then
    alter publication supabase_realtime add table public.sku_items;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'purchase_records'
  ) then
    alter publication supabase_realtime add table public.purchase_records;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'purchase_pools'
  ) then
    alter publication supabase_realtime add table public.purchase_pools;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'container_rows'
  ) then
    alter publication supabase_realtime add table public.container_rows;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'audit_logs'
  ) then
    alter publication supabase_realtime add table public.audit_logs;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'logistics_batches'
  ) then
    alter publication supabase_realtime add table public.logistics_batches;
  end if;

  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'logistics_batch_items'
  ) then
    alter publication supabase_realtime add table public.logistics_batch_items;
  end if;
end $$;

-- 2026-06-08 cleanup: price alerts keep current data only, audit logs are no longer used.
delete from public.repricing_snapshots;
drop table if exists public.audit_logs cascade;

-- 2026-06-10 SKU master data optional fields used by import/export and new product sync.
alter table public.sku_items
add column if not exists storage_location text;

alter table public.sku_items
add column if not exists purchase_url text;

-- 2026-07-22 广告分析：只保留最近三次分析结果，明细随 run 删除。
create table if not exists public.ad_analysis_runs (
  id text primary key,
  created_at timestamptz not null default now(),
  created_by text,
  source_file_name text,
  row_count numeric default 0,
  summary jsonb not null default '{}'::jsonb
);

create table if not exists public.ad_analysis_rows (
  id text primary key,
  run_id text not null references public.ad_analysis_runs(id) on delete cascade,
  sku text,
  product_id text,
  product_name text,
  shop_name text,
  image_url text,
  ad_spend numeric default 0,
  ad_sales_quantity numeric default 0,
  roas numeric,
  sale_price numeric default 0,
  platform_fee numeric default 0,
  platform_fee_source text,
  purchase_cost_rmb numeric default 0,
  purchase_cost_zar numeric default 0,
  unit_cbm numeric default 0,
  sea_freight_cost numeric default 0,
  warehouse_fee numeric default 0,
  ad_cost_per_sale numeric default 0,
  profit_rate numeric,
  sku_rank numeric,
  product_age_status text,
  strategy_label text,
  strategy_name text,
  action_suggestion text,
  messages text[] default '{}'
);

alter table public.ad_analysis_rows
add column if not exists product_id text;

create index if not exists ad_analysis_runs_created_idx
on public.ad_analysis_runs (created_at desc);

create index if not exists ad_analysis_rows_run_idx
on public.ad_analysis_rows (run_id);

alter table public.ad_analysis_runs enable row level security;
alter table public.ad_analysis_rows enable row level security;

drop policy if exists "shared select ad analysis runs" on public.ad_analysis_runs;
create policy "shared select ad analysis runs" on public.ad_analysis_runs for select to authenticated using (true);
drop policy if exists "editor insert ad analysis runs" on public.ad_analysis_runs;
create policy "editor insert ad analysis runs" on public.ad_analysis_runs for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update ad analysis runs" on public.ad_analysis_runs;
create policy "editor update ad analysis runs" on public.ad_analysis_runs for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "editor delete ad analysis runs" on public.ad_analysis_runs;
create policy "editor delete ad analysis runs" on public.ad_analysis_runs for delete to authenticated using (public.is_editor());

drop policy if exists "shared select ad analysis rows" on public.ad_analysis_rows;
create policy "shared select ad analysis rows" on public.ad_analysis_rows for select to authenticated using (true);
drop policy if exists "editor insert ad analysis rows" on public.ad_analysis_rows;
create policy "editor insert ad analysis rows" on public.ad_analysis_rows for insert to authenticated with check (public.is_editor());
drop policy if exists "editor update ad analysis rows" on public.ad_analysis_rows;
create policy "editor update ad analysis rows" on public.ad_analysis_rows for update to authenticated using (public.is_editor()) with check (public.is_editor());
drop policy if exists "editor delete ad analysis rows" on public.ad_analysis_rows;
create policy "editor delete ad analysis rows" on public.ad_analysis_rows for delete to authenticated using (public.is_editor());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'ad_analysis_runs'
  ) then
    alter publication supabase_realtime add table public.ad_analysis_runs;
  end if;
end $$;

-- 2026-08-04 利润分析：每个店铺仅保留最近一次完整同步结果。
create table if not exists public.profit_analysis_runs (
  id text primary key,
  shop_name text not null,
  created_at timestamptz not null default now(),
  created_by text,
  row_count numeric default 0,
  is_complete boolean not null default false
);

create table if not exists public.profit_analysis_rows (
  id text primary key,
  run_id text not null references public.profit_analysis_runs(id) on delete cascade,
  shop_name text not null,
  sku text not null,
  product_name text,
  image_url text,
  latest_order_date timestamptz,
  selling_price numeric,
  purchase_cost_rmb numeric,
  purchase_cost_zar numeric,
  unit_cbm numeric,
  sea_freight_cost numeric,
  domestic_freight_cost numeric,
  warehouse_fee numeric,
  total_fees numeric,
  profit numeric,
  status text not null,
  messages text[] default '{}',
  synced_at timestamptz not null default now(),
  unique (run_id, sku)
);

alter table public.profit_analysis_runs add column if not exists is_complete boolean not null default false;
alter table public.profit_analysis_rows add column if not exists domestic_freight_cost numeric;

create index if not exists profit_analysis_runs_shop_created_idx on public.profit_analysis_runs (shop_name, created_at desc);
create index if not exists profit_analysis_rows_run_idx on public.profit_analysis_rows (run_id);
alter table public.profit_analysis_runs enable row level security;
alter table public.profit_analysis_rows enable row level security;

drop policy if exists "admin select profit runs" on public.profit_analysis_runs;
create policy "admin select profit runs" on public.profit_analysis_runs for select to authenticated using (public.is_admin());
drop policy if exists "admin insert profit runs" on public.profit_analysis_runs;
create policy "admin insert profit runs" on public.profit_analysis_runs for insert to authenticated with check (public.is_admin());
drop policy if exists "admin update profit runs" on public.profit_analysis_runs;
create policy "admin update profit runs" on public.profit_analysis_runs for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin delete profit runs" on public.profit_analysis_runs;
create policy "admin delete profit runs" on public.profit_analysis_runs for delete to authenticated using (public.is_admin());
drop policy if exists "admin select profit rows" on public.profit_analysis_rows;
create policy "admin select profit rows" on public.profit_analysis_rows for select to authenticated using (public.is_admin());
drop policy if exists "admin insert profit rows" on public.profit_analysis_rows;
create policy "admin insert profit rows" on public.profit_analysis_rows for insert to authenticated with check (public.is_admin());
drop policy if exists "admin delete profit rows" on public.profit_analysis_rows;
create policy "admin delete profit rows" on public.profit_analysis_rows for delete to authenticated using (public.is_admin());

create table if not exists public.monthly_profit_summaries (
  id text primary key,
  shop_name text not null,
  month text not null,
  date_from date,
  date_to date,
  data_cutoff_date date not null,
  is_current_month boolean not null default false,
  sales_revenue numeric not null default 0,
  sales_quantity integer not null default 0,
  sales_profit numeric not null default 0,
  return_quantity integer not null default 0,
  return_profit_reversal numeric not null default 0,
  return_net_fees numeric not null default 0,
  advertising_cost numeric not null default 0,
  salary_cost numeric not null default 0,
  final_profit numeric not null default 0,
  missing_sales_quantity integer not null default 0,
  missing_sales_revenue numeric not null default 0,
  missing_return_quantity integer not null default 0,
  status text not null check (status in ('complete', 'incomplete')),
  note text,
  created_by text,
  updated_at timestamptz not null default now()
);

alter table public.monthly_profit_summaries add column if not exists salary_cost numeric not null default 0;
alter table public.monthly_profit_summaries add column if not exists date_from date;
alter table public.monthly_profit_summaries add column if not exists date_to date;
update public.monthly_profit_summaries
set date_from = coalesce(date_from, (month || '-01')::date),
    date_to = coalesce(date_to, case
      when data_cutoff_date between (month || '-01')::date and ((month || '-01')::date + interval '1 month - 1 day')::date then data_cutoff_date
      else ((month || '-01')::date + interval '1 month - 1 day')::date
    end)
where date_from is null or date_to is null;
alter table public.monthly_profit_summaries alter column date_from set not null;
alter table public.monthly_profit_summaries alter column date_to set not null;
alter table public.monthly_profit_summaries drop constraint if exists monthly_profit_summaries_shop_name_month_key;
create unique index if not exists monthly_profit_summaries_shop_range_idx on public.monthly_profit_summaries (shop_name, date_from, date_to);

alter table public.monthly_profit_summaries enable row level security;
drop policy if exists "owner select monthly profit" on public.monthly_profit_summaries;
create policy "owner select monthly profit" on public.monthly_profit_summaries for select to authenticated using (public.is_owner());
drop policy if exists "owner insert monthly profit" on public.monthly_profit_summaries;
create policy "owner insert monthly profit" on public.monthly_profit_summaries for insert to authenticated with check (public.is_owner());
drop policy if exists "owner update monthly profit" on public.monthly_profit_summaries;
create policy "owner update monthly profit" on public.monthly_profit_summaries for update to authenticated using (public.is_owner()) with check (public.is_owner());
drop policy if exists "owner delete monthly profit" on public.monthly_profit_summaries;
create policy "owner delete monthly profit" on public.monthly_profit_summaries for delete to authenticated using (public.is_owner());

-- 2026-08-25 采购人提成：按 Takealot Sales 和 Selling Price 计算，并保留历史结果用于导出。
create table if not exists public.commission_runs (
  id text primary key,
  shop_name text not null,
  date_from date not null,
  date_to date not null,
  created_at timestamptz not null default now(),
  created_by text,
  row_count numeric not null default 0,
  total_sales_quantity numeric not null default 0,
  total_sales_revenue_zar numeric not null default 0,
  total_sales_revenue_rmb numeric not null default 0,
  total_commission_rmb numeric not null default 0,
  buyer_summaries jsonb not null default '[]'::jsonb,
  rows jsonb not null default '[]'::jsonb,
  exceptions jsonb not null default '[]'::jsonb
);

create index if not exists commission_runs_created_idx on public.commission_runs (created_at desc);

alter table public.commission_runs enable row level security;

drop policy if exists "admin select commission runs" on public.commission_runs;
create policy "admin select commission runs" on public.commission_runs for select to authenticated using (public.is_admin());
drop policy if exists "admin insert commission runs" on public.commission_runs;
create policy "admin insert commission runs" on public.commission_runs for insert to authenticated with check (public.is_admin());
drop policy if exists "admin update commission runs" on public.commission_runs;
create policy "admin update commission runs" on public.commission_runs for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admin delete commission runs" on public.commission_runs;
create policy "admin delete commission runs" on public.commission_runs for delete to authenticated using (public.is_admin());

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'commission_runs'
  ) then
    alter publication supabase_realtime add table public.commission_runs;
  end if;
end $$;

do $$
declare
  v_table text;
begin
  foreach v_table in array array[
    'haichuan_inbound_items',
    'haichuan_warehouse_lots',
    'haichuan_loading_batches',
    'haichuan_loading_items'
  ]
  loop
    if not exists (
      select 1 from pg_publication_tables
      where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = v_table
    ) then
      execute format('alter publication supabase_realtime add table public.%I', v_table);
    end if;
  end loop;
end $$;
